version: '3.9'

services:
  web:
    expose:
      - "8000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - XXXX=123
    restart: always
    volumes:
      - .:/opt/app
