version: '3.9'

services:
  web:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - XXXX=123
    restart: always
    volumes:
      - .:/opt/app
