name: RELEASE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo curl -X POST http://deploy.cloud.aplicativo.click/ -d '{"action": "deploy", "project": "${{ github.repositoryUrl }}", "token": ""}'
